<a href="https://colab.research.google.com/github/ankit-kr6/LEARNING-ML/blob/main/video_27.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
!kaggle datasets download -d sikandarfarooqsaani/cars-dataset-campusx

Dataset URL: https://www.kaggle.com/datasets/sikandarfarooqsaani/cars-dataset-campusx
License(s): apache-2.0
cars-dataset-campusx.zip: Skipping, found more recently modified local copy (use --force to force download)

In [60]:
import zipfile
with zipfile.ZipFile('cars-dataset-campusx.zip', 'r') as zip_ref:
    zip_ref.extractall('/content')

In [61]:
import numpy as np
import pandas as pd

In [62]:
df=pd.read_csv('cars (2).csv')

In [63]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

OneHotEncoding using pandas

In [64]:
pd.get_dummies(df, columns=['fuel', 'owner'], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

K-1 OneHotEncoding using Skleran

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 0:4], df.iloc[:, -1], test_size=0.2, random_state=2)

In [66]:
X_train

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner
...        ...        ...     ...           ...
3606      Ford      35000  Diesel   First Owner
5704    Maruti     120000  Petrol   First Owner
6637      Tata      15000  Petrol   First Owner
2575    Maruti      32500  Diesel  Second Owner
7336     Isuzu     121000  Diesel   First Owner

[6502 rows x 4 columns]

In [67]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [68]:

X_train_new=ohe.fit_transform(X_train[['fuel', 'owner']])
X_test_new=ohe.transform(X_test[['fuel', 'owner']])

In [69]:
X_train_new.shape

(6502, 7)

In [71]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

In [73]:
counts=df['brand'].value_counts()

In [74]:
df['brand'].nunique()
threshold=100

In [75]:
repl=counts[counts<=threshold].index

In [77]:
pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
3126,False,False,False,False,True,False,False,False,False,False,False,False,False
729,False,False,False,False,False,False,False,False,False,True,False,False,False
5388,False,False,False,False,True,False,False,False,False,False,False,False,False
653,False,False,False,False,False,False,True,False,False,False,False,False,False
1399,False,False,False,False,False,False,False,False,False,False,True,False,False