<a href="https://colab.research.google.com/github/ankit-kr6/LEARNING-ML/blob/main/video_39.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!kaggle datasets download -d hesh97/titanicdataset-traincsv

Dataset URL: https://www.kaggle.com/datasets/hesh97/titanicdataset-traincsv
License(s): CC0-1.0
Downloading titanicdataset-traincsv.zip to /content
100% 22.0k/22.0k [00:00<00:00, 9.73MB/s]

In [2]:
import zipfile
with zipfile.ZipFile('titanicdataset-traincsv.zip', 'r') as zip_ref:
    zip_ref.extractall('/content')

In [13]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [5]:
df=pd.read_csv('/content/train.csv')[['Age','Pclass','Fare','Survived']]
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [6]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [7]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [9]:
x_train.head()

      Age  Pclass     Fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000
182   9.0       3  31.3875
876  20.0       3   9.8458

In [21]:
knn=KNNImputer(n_neighbors=100,weights='distance')
x_train_trf=knn.fit_transform(x_train)
x_test_trf=knn.transform(x_test)

In [22]:
pd.DataFrame(x_train_trf,columns=x_train.columns)

           Age  Pclass      Fare
0    40.000000     1.0   27.7208
1     4.000000     3.0   16.7000
2    47.000000     3.0    9.0000
3     9.000000     3.0   31.3875
4    20.000000     3.0    9.8458
..         ...     ...       ...
707  30.000000     3.0    8.6625
708  26.649367     3.0    8.7125
709  71.000000     1.0   49.5042
710  32.391761     1.0  221.7792
711  46.692731     1.0   25.9250

[712 rows x 3 columns]

In [23]:
lr=LogisticRegression()
lr.fit(x_train_trf,y_train)
y_pred=lr.predict(x_test_trf)
accuracy_score(y_test,y_pred)

0.7039106145251397

In [26]:
#comparision with simpelImputer
si = SimpleImputer()
x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [27]:
lr = LogisticRegression()
lr.fit(x_train_trf2,y_train)
y_pred2 = lr.predict(x_test_trf2)
accuracy_score(y_test,y_pred2)

0.6927374301675978